<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.benchmarx</groupId>
    <artifactId>benchmarxUpdates-parent</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <relativePath>../../pom.xml</relativePath>
  </parent>

  <artifactId>gantttocpm-parent</artifactId>
  <packaging>pom</packaging>
  <name>BenchmarX - Gantt to CPM (Parent)</name>

  <modules>
    <module>metamodels/Gantt</module>
    <module>metamodels/CPM</module>
    <module>BenchmarxGanttToCPM</module>
  </modules>

</project>
