package org.benchmarx.dsl.generator.templates

import org.benchmarx.dsl.benchmarxDSL.ProblemDecl

class ComparatorStubTemplate {

	def srcComparatorStub(ProblemDecl p) '''
		package org.benchmarx.examples.«p.name.toLowerCase».comparator;

		import org.benchmarx.comparator.BenchmarxComparator;

		/**
		 * Comparator for the SOURCE model of «p.name».
		 * Stub generated by BenchmarxDSLGenerator.
		 * Add your implementation here — this file will NOT be regenerated.
		 */
		public class «p.name»SrcComparator
		        extends BenchmarxComparator<Object /* TODO: replace with real source root type */> {

		    @Override
		    protected String modelName() { return "«p.name»Source"; }
		}
	'''

	def trgComparatorStub(ProblemDecl p) '''
		package org.benchmarx.examples.«p.name.toLowerCase».comparator;

		import org.benchmarx.comparator.BenchmarxComparator;

		/**
		 * Comparator for the TARGET model of «p.name».
		 * Stub generated by BenchmarxDSLGenerator.
		 * Add your implementation here — this file will NOT be regenerated.
		 */
		public class «p.name»TrgComparator
		        extends BenchmarxComparator<Object /* TODO: replace with real target root type */> {

		    @Override
		    protected String modelName() { return "«p.name»Target"; }
		}
	'''
}
