package org.benchmarx.dsl.generator.templates

import java.util.LinkedHashSet
import org.benchmarx.dsl.benchmarxDSL.ProblemDecl
import org.benchmarx.dsl.benchmarxDSL.SuiteDecl

class HelperStubTemplate {

	def srcHelperStub(ProblemDecl p, SuiteDecl suite) '''
		package org.benchmarx.examples.«p.name.toLowerCase».helpers;

		/**
		 * Named edit operations on the SOURCE model for «p.name».
		 * Stub generated by BenchmarxDSLGenerator.
		 * Add your implementation here — this file will NOT be regenerated.
		 */
		public class «p.name»SrcHelper {
		    «FOR opName : allOps(suite, "source")»

		    /** TODO: implement «opName» */
		    public void «opName»() {
		        throw new UnsupportedOperationException("«opName» not yet implemented");
		    }
		    «ENDFOR»
		}
	'''

	def trgHelperStub(ProblemDecl p, SuiteDecl suite) '''
		package org.benchmarx.examples.«p.name.toLowerCase».helpers;

		/**
		 * Named edit operations on the TARGET model for «p.name».
		 * Stub generated by BenchmarxDSLGenerator.
		 * Add your implementation here — this file will NOT be regenerated.
		 */
		public class «p.name»TrgHelper {
		    «FOR opName : allOps(suite, "target")»

		    /** TODO: implement «opName» */
		    public void «opName»() {
		        throw new UnsupportedOperationException("«opName» not yet implemented");
		    }
		    «ENDFOR»
		}
	'''

	def private allOps(SuiteDecl suite, String side) {
		if (suite === null) return #[]
		val ops = new LinkedHashSet<String>
		for (test : suite.tests) {
			for (step : test.setup)
				if (step.side == side) ops.addAll(step.ops)
			for (edit : test.edits)
				if (edit.side == side) ops.addAll(edit.ops)
		}
		ops.toList
	}
}
