bin.includes = META-INF/,\
               src/,\
               lib/bxagent-pdb12pdb2-1.0.0.jar,\
               lib/bxtend-pdb12pdb2-1.0.0.jar,\
               lib/bxlang-pdb12pdb2.jar,\
               lib/bx-runtime-1.0.0-SNAPSHOT.jar,\
               lib/mediniQVT/
jars.compile.order = .
source.. = src/
 = resources/
output.. = bin/
